$input v_normal, v_texcoord

/*
 * DON'T CHANGE DIRECTLY
 * This is a fragment shader header file generated by aderite for material ColorMaterial
 * Generated at 2022-05-28 19.24.45
 */

// Libraries
#include "bgfx_shader.sh"
#include "shaderLib.sh"
#include "material_4.sh"

// Constants

// Functions
void main() {
	// ColorMaterial
	vec3 ColorMaterial_Color = mf_ColorMaterial_Color;
	BgfxSampler2D ColorMaterial_Texture = mf_ColorMaterial_Texture;
	// ptToOViTRWgq
	float ptToOViTRWgq_Value = 0.000000;
	// A8VjkjkYVCNz
	vec4 A8VjkjkYVCNz_Out = vec4(ColorMaterial_Color, ptToOViTRWgq_Value);
	// yT1lRuhFRFRP
	vec2 yT1lRuhFRFRP_v_texcoord = v_texcoord;
	// b2x88AFBLyI3
	vec4 b2x88AFBLyI3_Color = texture2D(ColorMaterial_Texture, yT1lRuhFRFRP_v_texcoord);
	// YhC10xPFPOSx
	vec4 YhC10xPFPOSx_Sum = A8VjkjkYVCNz_Out + b2x88AFBLyI3_Color;
	// RnbsmCISjK6i
	gl_FragColor = YhC10xPFPOSx_Sum;
}
