/*
 * DON'T CHANGE DIRECTLY
 * This is a shader header file generated by aderite for material Material
 * Generated at 2022-05-28 19.36.30
 */

uniform vec4 mf_mat_buffer_Material[1];

// Properties
#define mf_Material_Color mf_mat_buffer_Material[0].xyz

// Samplers
SAMPLER2D(mf_Material_Texture, 0);
