/*
 * DON'T CHANGE DIRECTLY
 * This is a shader header file generated by aderite for material ColorMaterial
 * Generated at 2022-05-28 19.24.45
 */

uniform vec4 mf_mat_buffer_ColorMaterial[1];

// Properties
#define mf_ColorMaterial_Color mf_mat_buffer_ColorMaterial[0].xyz

// Samplers
SAMPLER2D(mf_ColorMaterial_Texture, 0);
