/*
 * DON'T CHANGE DIRECTLY
 * This is a shader header file generated by aderite for material 5
 * Generated at 2021-11-02 15.00.18
 */

uniform vec4 u_mat_buffer_5[1];

// Properties
#define u_5_Color u_mat_buffer_5[0].xyzw

// Samplers
SAMPLER2D(u_5_Texture, 0);
