$input v_normal, v_texcoord

/*
 * DON'T CHANGE DIRECTLY
 * This is a fragment shader header file generated by aderite for material ColorShift
 * Generated at 2021-12-18 00.25.36
 */

// Libraries
#include "bgfx_shader.sh"
#include "shaderLib.sh"
#include "material_7.sh"

// Constants

// Functions
void main() {
	// ColorShift
	vec3 ColorShift_p_Color = mf_ColorShift_p_Color;
	BgfxSampler2D ColorShift_s_Texture = mf_ColorShift_s_Texture;
	// mQyi5vJ3zpi6
	float mQyi5vJ3zpi6_Value = 0.000000;
	// uKfhWDBUUy1z
	vec4 uKfhWDBUUy1z_Out = vec4(ColorShift_p_Color, mQyi5vJ3zpi6_Value);
	// qB6MH0C7wDOb
	vec2 qB6MH0C7wDOb_v_texcoord = v_texcoord;
	// j9ZlDxNqyC70
	vec4 j9ZlDxNqyC70_Color = texture2D(ColorShift_s_Texture, qB6MH0C7wDOb_v_texcoord);
	// p7kxbwIWcjvC
	vec4 p7kxbwIWcjvC_Sum = uKfhWDBUUy1z_Out + j9ZlDxNqyC70_Color;
	// XBUjmkgKeuT3
	gl_FragColor = p7kxbwIWcjvC_Sum;
}
