$input v_normal, v_texcoord

/*
 * DON'T CHANGE DIRECTLY
 * This is a fragment shader header file generated by aderite for material Textured
 * Generated at 2021-12-07 21.09.35
 */

// Libraries
#include "bgfx_shader.sh"
#include "shaderLib.sh"
#include "material_3.sh"

// Constants

// Functions
void main() {
	// Textured
	BgfxSampler2D Textured_s_Texture = mf_Textured_s_Texture;
	// EM2DxVHLX06z
	vec2 EM2DxVHLX06z_v_texcoord = v_texcoord;
	// c4QdgRNmZ2Sw
	vec4 c4QdgRNmZ2Sw_Color = texture2D(Textured_s_Texture, EM2DxVHLX06z_v_texcoord);
	// 4fQ9zCc4HQQa
	gl_FragColor = c4QdgRNmZ2Sw_Color;
}
