/*
 * DON'T CHANGE DIRECTLY
 * This is a shader header file generated by aderite for material Textured
 * Generated at 2021-12-08 20.27.03
 */

// Properties

// Samplers
SAMPLER2D(mf_Textured_s_Texture, 0);
