/*
 * DON'T CHANGE DIRECTLY
 * This is a shader header file generated by aderite for material ColorShift
 * Generated at 2021-12-18 12.05.56
 */

uniform vec4 mf_mat_buffer_ColorShift[1];

// Properties
#define mf_ColorShift_p_Color mf_mat_buffer_ColorShift[0].xyz

// Samplers
SAMPLER2D(mf_ColorShift_s_Texture, 0);
