$input v_normal, v_texcoord

/*
 * DON'T CHANGE DIRECTLY
 * This is a fragment shader header file generated by aderite for material ImageMaterialType_mtype
 * Generated at 2021-10-11 15.12.07
 */

#include "bgfx_shader.sh"
#include "ImageMaterialType_mtype.sh"

void main()
{
	gl_FragColor = u_ImageMaterialType_mtype_NewProperty_259e7581;
}
