$input v_normal, v_texcoord

/*
 * DON'T CHANGE DIRECTLY
 * This is a fragment shader header file generated by aderite for material ImageMaterialType_mtype
 * Generated at 2021-10-11 16.11.54
 */

#include "bgfx_shader.sh"
#include "shaderLib.sh"
#include "ImageMaterialType_mtype.sh"

void main()
{
	vec4 texcolor = toLinear(texture2D(s_ImageMaterialType_mtype_NewProperty_edee790d, v_texcoord));
	gl_FragColor = texcolor + u_ImageMaterialType_mtype_NewProperty_259e7581;
}
