/*
 * DON'T CHANGE DIRECTLY
 * This is a shader header file generated by aderite for material ImageMaterialType.mtype
 * Generated at 2021-10-11 12.02.50
 */

uniform vec4 u_mat_buffer_ImageMaterialType.mtype[4]

// Properties
#define u_ImageMaterialType.mtype_NewProperty_b5d338cd u_mat_buffer_ImageMaterialType.mtype[1].xyz
#define u_ImageMaterialType.mtype_NewProperty_092afff1 u_mat_buffer_ImageMaterialType.mtype[3].x
#define u_ImageMaterialType.mtype_NewProperty_9035d32e u_mat_buffer_ImageMaterialType.mtype[2].xy
#define u_ImageMaterialType.mtype_NewProperty_08a8c198 u_mat_buffer_ImageMaterialType.mtype[2].zw
#define u_ImageMaterialType.mtype_NewProperty_965a2e34 u_mat_buffer_ImageMaterialType.mtype[3].y
#define u_ImageMaterialType.mtype_NewProperty_b942a4ef u_mat_buffer_ImageMaterialType.mtype[1].w
#define u_ImageMaterialType.mtype_NewProperty_259e7581 u_mat_buffer_ImageMaterialType.mtype[0].xyzw

// Samplers
SAMPLERCUBE(s_mat_ImageMaterialType.mtype_NewProperty_96664f36, 0);
SAMPLER2D(s_mat_ImageMaterialType.mtype_NewProperty_edee790d, 1);

