/*
 * DON'T CHANGE DIRECTLY
 * This is a shader header file generated by aderite for material ImageMaterialType_mtype
 * Generated at 2021-10-12 16.45.22
 */

uniform vec4 u_mat_buffer_ImageMaterialType_mtype[4];

// Properties
#define ImageMaterialType_mtype_NewProperty_b5d338cd u_mat_buffer_ImageMaterialType_mtype[1].xyz
#define ImageMaterialType_mtype_NewProperty_092afff1 u_mat_buffer_ImageMaterialType_mtype[3].x
#define ImageMaterialType_mtype_NewProperty_9035d32e u_mat_buffer_ImageMaterialType_mtype[2].xy
#define ImageMaterialType_mtype_NewProperty_08a8c198 u_mat_buffer_ImageMaterialType_mtype[2].zw
#define ImageMaterialType_mtype_NewProperty_965a2e34 u_mat_buffer_ImageMaterialType_mtype[3].y
#define ImageMaterialType_mtype_NewProperty_b942a4ef u_mat_buffer_ImageMaterialType_mtype[1].w
#define ImageMaterialType_mtype_NewProperty_259e7581 u_mat_buffer_ImageMaterialType_mtype[0].xyzw

// Samplers
SAMPLERCUBE(ImageMaterialType_mtype_NewProperty_96664f36, 0);
SAMPLER2D(ImageMaterialType_mtype_NewProperty_edee790d, 1);

