$input a_position, a_normal, a_texcoord0
$output v_normal, v_texcoord

/*
 * DON'T CHANGE DIRECTLY
 * This is a vertex shader header file generated by aderite for material ImageMaterialType_mtype
 * Generated at 2021-10-12 18.11.23
 */

#include "bgfx_shader.sh"
#include "shaderLib.sh"
#include "ImageMaterialType_mtype.sh"

void main()
{
	gl_Position = mul(u_modelViewProj, vec4(a_position, 1.0));
	v_texcoord = a_texcoord0;
	v_normal = a_normal;
}
