$input v_normal, v_texcoord

/*
 * DON'T CHANGE DIRECTLY
 * This is a fragment shader header file generated by aderite for material 3
 * Generated at 2021-10-25 13.47.51
 */

// Libraries
#include "bgfx_shader.sh"
#include "shaderLib.sh"
#include "material_3.sh"

// Constants

// Functions
void main() {
	vec4 vY3rhke0VFrvmdL14 = texture2D(u_3_Texture, v_texcoord);
	vec4 vqaxFSV5JQsxcOX5Y = u_3_Color + vY3rhke0VFrvmdL14;
	gl_FragColor = vqaxFSV5JQsxcOX5Y;
}
