$input v_normal, v_texcoord

/*
 * DON'T CHANGE DIRECTLY
 * This is a fragment shader header file generated by aderite for material 3
 * Generated at 2021-10-24 16.23.49
 */

// Libraries
#include "bgfx_shader.sh"
#include "shaderLib.sh"
#include "material_3.sh"

// Constants

// Functions
void main() {
	vec4 vx7cYrkHVzavJa5ZV = texture2D(u_3_Texture, v_texcoord);
	vec4 vHV63Qva0mLA0yLE3 = u_3_Color + vx7cYrkHVzavJa5ZV;
	gl_FragColor = vHV63Qva0mLA0yLE3;
}
