/*
 * DON'T CHANGE DIRECTLY
 * This is a shader header file generated by aderite for material 3
 * Generated at 2021-10-24 16.23.49
 */

uniform vec4 u_mat_buffer_3[1];

// Properties
#define u_3_Color u_mat_buffer_3[0].xyzw

// Samplers
SAMPLER2D(u_3_Texture, 0);
