$input v_normal, v_texcoord

/*
 * DON'T CHANGE DIRECTLY
 * This is a fragment shader header file generated by aderite for material ColorMaterial
 * Generated at 2022-05-25 22.44.22
 */

// Libraries
#include "bgfx_shader.sh"
#include "shaderLib.sh"
#include "material_3.sh"

// Constants

// Functions
void main() {
	// ColorMaterial
	vec3 ColorMaterial_p_Color = mf_ColorMaterial_p_Color;
	BgfxSampler2D ColorMaterial_s_Texture = mf_ColorMaterial_s_Texture;
	// Y3kY6SeiGPlT
	float Y3kY6SeiGPlT_Value = 0.000000;
	// UUmNj1qmdZ9h
	vec4 UUmNj1qmdZ9h_Out = vec4(ColorMaterial_p_Color, Y3kY6SeiGPlT_Value);
	// KnKpZ1P5NsgY
	vec2 KnKpZ1P5NsgY_v_texcoord = v_texcoord;
	// mdAnJBEFHVW0
	vec4 mdAnJBEFHVW0_Color = texture2D(ColorMaterial_s_Texture, KnKpZ1P5NsgY_v_texcoord);
	// oMOAOGxtTtGH
	vec4 oMOAOGxtTtGH_Sum = UUmNj1qmdZ9h_Out + mdAnJBEFHVW0_Color;
	// ZKqKMxwQ6izn
	gl_FragColor = oMOAOGxtTtGH_Sum;
}
