/*
 * DON'T CHANGE DIRECTLY
 * This is a shader header file generated by aderite for material ExampleType
 * Generated at 2022-05-28 20.08.01
 */

// Properties

// Samplers
SAMPLER2D(mf_ExampleType_Texture, 0);
